blog_redo/blog/urls.py
from django.urls import path
from . import views


app_name = 'blog'
urlpatterns = [
    path('', views.index, name='index'),
    path('post/<int:pk>', views.detail, name='detail'),
    path('archives/<int:year>/<int:month>', views.archives, name='archives'),
    path('new_post', views.new_post, name='new_post'),
    path('posts', views.posts, name='posts')
]

blog_redo/blog_redo/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog_redo/blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from ckeditor_uploader.fields import RichTextUploadingField


class Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Tag(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Post(models.Model):
    # 标题
    title = models.CharField(max_length=70)

    # 正文
    body = RichTextUploadingField(config_name='default')

    # 时间
    created_time = models.DateTimeField()
    modified_time = models.DateTimeField()

    # excerpt
    excerpt = models.CharField(max_length=200, blank=True)

    category = models.ForeignKey(Category, on_delete=True)
    tags = models.ManyToManyField(Tag, blank=True)

    author = models.ForeignKey(User, on_delete=True)

    image = models.ImageField(upload_to='upload/carousel/%Y/%m/%d', blank=True)

    class Meta:
        ordering = ['-created_time']

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:detail', kwargs={'pk': self.pk})


# user
class UserPost(models.Model):
    # 标题
    title = models.CharField(max_length=70)

    # 正文
    body = RichTextUploadingField(config_name='default')

    # 时间
    created_time = models.DateField(auto_now_add=True)

    # excerpt
    # excerpt = models.CharField(max_length=200, blank=True)

    author = models.ForeignKey(User, on_delete=True)

    # image = models.ImageField(upload_to='upload/user/%Y/%m/%d', blank=True)

    class Meta:
        ordering = ['-created_time']

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:detail', kwargs={'pk': self.pk})

blog_redo/blog/forms.py
from django import forms

from .models import UserPost


class UserPostForm(forms.ModelForm):
    class Meta:
        model = UserPost
        fields = ['title', 'body', 'author']

blog_redo/blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post,UserPost
from .forms import UserPostForm
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import HttpResponseRedirect
from django.urls import reverse


def index(request):
    """首页"""
    post_list = Post.objects.all().order_by('-created_time')
    paginator = Paginator(post_list, 3)  # 每页显示 3 个联系人

    page = request.GET.get('page')
    try:
        post_list = paginator.page(page)
    except PageNotAnInteger:
        # 如果用户请求的页码号不是整数，显示第一页
        post_list = paginator.page(1)
    except EmptyPage:
        # 如果用户请求的页码号超过了最大页码号，显示最后一页
        post_list = paginator.page(paginator.num_pages)
    return render(request, 'blog/index.html', {'post_list': post_list})


def detail(request, pk):
    """详情页（个人）"""
    post = get_object_or_404(Post, pk=pk)
    return render(request, 'blog/detail.html', context={'post': post})


def archives(request, year, month):
    """归档（个人）"""
    num = 10
    post_list = Post.objects.filter(created_time__year=year,
                                    created_time__month=month
                                    ).order_by('-created_time')[:num]
    return render(request, 'blog/archives.html', context={'date_list': post_list})


def new_post(request):
    """添加新主题"""
    if request.method != 'POST':
        form = UserPostForm()
    else:
        form = UserPostForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('blog:posts'))

    context = {'form': form}
    return render(request, 'blog/new_post.html', context=context)


def posts(request):
    """首页"""
    post_list = UserPost.objects.all().order_by('-created_time')
    paginator = Paginator(post_list, 10)  # 每页显示 3 个联系人

    page = request.GET.get('page')
    try:
        post_list = paginator.page(page)
    except PageNotAnInteger:
        # 如果用户请求的页码号不是整数，显示第一页
        post_list = paginator.page(1)
    except EmptyPage:
        # 如果用户请求的页码号超过了最大页码号，显示最后一页
        post_list = paginator.page(paginator.num_pages)
    return render(request, 'blog/posts.html', {'post_list': post_list})

blog_redo/templates/blog/archives.html
{% extends 'blog/base.html' %}
{% load static %}
{% load blog_tags %}

{% block top-slider %}
  <section class="container  top-slider">
      <div class="col-md-12">
        <div class="bxslider">
          <div>
            <div class="featured-image" style="background-image:url({% static 'blog/img/img1.jpg' %});">
              <div class="featured-image__bg"></div>
              <div class="featured-image__content">
                <span class="featured-image__content-category">
                  <a href="#">Lifestyle</a>
                </span>
                <span class="featured-image__content-title">
                  <a href="single-post.html">Fall In Love With Cat</a>
                </span>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse lobortis commodo ullamcorper.</p>
                <span class="featured-image__content-link">
                  <a href="single-post.html">Read More</a>
                </span>
              </div>
            </div>
          </div>
          <div>
            <div class="featured-image" style="background-image:url({% static 'blog/img/img2.jpg' %});">
              <div class="featured-image__bg"></div>
              <div class="featured-image__content">
                <span class="featured-image__content-category">
                  <a href="#">Journey</a>
                </span>
                <span class="featured-image__content-title">
                  <a href="single-post.html">All You Need To Know About Forest</a>
                </span>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse lobortis commodo ullamcorper.</p>
                <span class="featured-image__content-link">
                  <a href="single-post.html">Read More</a>
                </span>
              </div>
            </div>
          </div>
          <div>
            <div class="featured-image" style="background-image:url({% static 'blog/img/img3.jpg' %});">
              <div class="featured-image__bg"></div>
              <div class="featured-image__content">
                <span class="featured-image__content-category">
                  <a href="#">Lifestyle</a>
                </span>
                <span class="featured-image__content-title">
                  <a href="single-post.html">Skills That You Can Learn From Book</a>
                </span>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse lobortis commodo ullamcorper.</p>
                <span class="featured-image__content-link">
                  <a href="single-post.html">Read More</a>
                </span>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
{% endblock top-slider %}

{% block container %}
  <div class="container">
        <div class="col-md-9">
        {% for post in post_list %}
          <div class="blog-post">
            <div class="blog-post-wrapper">
              <div class="blog-post__info  blog-post__info--top">
                <span><a href="#">{{ post.category }}</a></span>
              </div>
              <div class="blog-post__title">
                <h2><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h2>
              </div>
              <div class="blog-post__info">
                <span>By <a href="#">{{ post.author }}</a></span>
                <span>{{ post.created_time }}</span>
                <span><a href="#">1 Comments</a></span>
              </div>
            </div>
            <div class="blog-post-wrapper">
              <div class="blog-post__content">
                <p>{{ post.excerpt|safe }}</p>
              </div>
              <div class="blog-post__footer">
                <a class="blog-post__footer-link" href="{{ post.get_absolute_url }}">Read more</a>
                <div class="blog-post__footer-social">
                  <span>Share:</span>
                  <div class="blog-post__footer-social-icons">
                    <a href="#">
                      <svg>
                        <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#icon-facebook"></use>
                      </svg>
                    </a>
                    <a href="#">
                      <svg>
                        <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#icon-twitter"></use>
                      </svg>
                    </a>
                    <a href="#">
                      <svg>
                        <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#icon-google"></use>
                      </svg>
                    </a>
                    <a href="#">
                      <svg>
                        <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#icon-pinterest"></use>
                      </svg>
                    </a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        {% empty %}
          <a>你暂时没有发布任何文章！</a>
        {% endfor %}
          <nav class="blog-pagination">
            <ul class="blog-pagination__items">
              <li class="blog-pagination__item  blog-pagination__item--active">
                <a>1</a>
              </li>
              <li class="blog-pagination__item">
                <a href="#">2</a>
              </li>
              <li class="blog-pagination__item">
                <a href="#">Next Page</a>
              </li>
            </ul>
          </nav>
        </div>
        <div class="col-md-3  sidebar  sidebar--right">
          <div class="sidebar-widget">
            <h3>About Me</h3>
            <div class="sidebar-widget__about-me">
              <div class="sidebar-widget__about-me-image">
                <img src="{% static 'blog/img/about-me.jpg' %}" alt="About Me">
              </div>
              <p>Do believe the faith in what you're doing and don't panic.</p>
              <span class="sidebar-widget__about-me-link">
                <a href="about.html">我我我</a>
              </span>
            </div>
          </div>
          <div class="sidebar-widget">
            <h3>Follow Me</h3>
            <div class="sidebar-widget__follow-me">
              <div class="sidebar-widget__follow-me-icons">
                <a href="#">
                  <svg>
                    <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#icon-facebook"></use>
                  </svg>
                </a>
                <a href="#">
                  <svg>
                    <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#icon-twitter"></use>
                  </svg>
                </a>
                <a href="#">
                  <svg>
                    <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#icon-google"></use>
                  </svg>
                </a>
                <a href="#">
                  <svg>
                    <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#icon-pinterest"></use>
                  </svg>
                </a>
                <a href="#">
                  <svg>
                    <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#icon-instagram"></use>
                  </svg>
                </a>
              </div>
            </div>
          </div>
          <div class="sidebar-widget">
            <h3>Recent Posts</h3>
            <div class="sidebar-widget__popular">
              {% get_recent_posts as recent_posts_list %}
                {% for post in recent_posts_list %}
                <div class="sidebar-widget__popular-item">
                <div class="sidebar-widget__popular-item-image">
                  <a href="single-post.html"><img src="{% static 'blog/img/sidebar1.jpg' %}" alt="7 Quick Tips For Coffee"></a>
                </div>
                <div class="sidebar-widget__popular-item-info">
                  <div class="sidebar-widget__popular-item-date">
                    <span>{{ post.created_time }}</span>
                  </div>
                  <div class="sidebar-widget__popular-item-content">
                    <a href="single-post.html">{{ post.title }}</a>
                  </div>
                </div>
              </div>
                {% empty %}
                 暂无文章！
                {% endfor %}
            </div>
          </div>
          <div class="sidebar-widget">
            <h3>Category Cloud</h3>
            <div class="sidebar-widget__tag-cloud">
              {% get_categories as category_list %}
                {% for category in category_list %}
                  <a href="#">{{ category.name }}</a>
                {% empty %}
                 暂无分类！
                {% endfor %}
            </div>
          </div>
          <div class="sidebar-widget">
            <h3>Tag Cloud</h3>
            <div class="sidebar-widget__tag-cloud">
              {% get_tags as tag_list %}
                {% for tag in tag_list %}
                  <a href="#">{{ tag.name }}</a>
                {% empty %}
                 暂无分类！
                {% endfor %}
            </div>
          </div>
          <div class="sidebar-widget">
            <h3>Subscribe</h3>
            <div class="sidebar-widget__subscribe">
              <p>Follow my latest news</p>
              <form action="index.html">
                <input type="text" placeholder="Your email">
                <input class="sidebar-widget__subscribe-submit" type="submit" value="Submit">
              </form>
            </div>
          </div>
          <div class="sidebar-widget">
            <div class="sidebar-slider">
              <div>
                <div class="featured-image" style="background-image:url(img/img1.jpg);">
                  <div class="featured-image__bg"></div>
                  <div class="featured-image__content">
                    <span class="featured-image__content-category">
                      <a href="#">Here</a>
                    </span>
                    <span class="featured-image__content-title">
                      <a href="single-post.html">For Advertisement</a>
                    </span>
                    <span class="featured-image__content-link">
                      <a href="single-post.html">CONTACT ME</a>
                    </span>
                  </div>
                  <a class="featured-image__overlay-link" href="single-post.html"></a>
                </div>
              </div>
              <div>
                <div class="featured-image" style="background-image:url(img/img0.jpg);">
                  <div class="featured-image__bg"></div>
                  <div class="featured-image__content">
                    <span class="featured-image__content-category">
                      <a href="#">Inspiration</a>
                    </span>
                    <span class="featured-image__content-title">
                      <a href="single-post.html">Why Glass Had Been So Popular Till Now?</a>
                    </span>
                    <span class="featured-image__content-link">
                      <a href="single-post.html">Read More</a>
                    </span>
                  </div>
                  <a class="featured-image__overlay-link" href="single-post.html"></a>
                </div>
              </div>
              <div>
                <div class="featured-image" style="background-image:url(img/img3.jpg);">
                  <div class="featured-image__bg"></div>
                  <div class="featured-image__content">
                    <span class="featured-image__content-category">
                      <a href="#">Lifestyle</a>
                    </span>
                    <span class="featured-image__content-title">
                      <a href="single-post.html">Skills That You Can Learn From Book</a>
                    </span>
                    <span class="featured-image__content-link">
                      <a href="single-post.html">Read More</a>
                    </span>
                  </div>
                  <a class="featured-image__overlay-link" href="single-post.html"></a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
{% endblock container %}

blog_redo/templates/blog/detail.html
{% extends 'blog/base.html' %}
{% load static %}


{% block container %}
  <div class="container">
        <div class="col-md-12">
          <div class="blog-post  blog-post--fullwidth">
            <div class="blog-post-wrapper">
              <div class="blog-post__info  blog-post__info--top">
                <span><a href="#">Lifestyle</a></span>
              </div>
              <div class="blog-post__title">
                <h1><a href="single-post.html">{{ post.title }}</a></h1>
              </div>
              <div class="blog-post__info">
                <span>By <a href="#">{{ post.author }}</a></span>
                <span>{{ post.created_time }}</span>
                <span><a href="#">3 Comments</a></span>
              </div>
            </div>
            <div class="blog-post__image">
              <a href="#"><img src="{{ post.image.url }}" alt="This should be an image"></a>
            </div>
            <div class="blog-post-wrapper">
              <div class="blog-post__content">
                <p>{{ post.body|safe }}</p>
              </div>
              <div class="blog-post__footer">
                <div class="blog-post__footer-tags">
                  <h3>Tags:</h3>
                  <div class="blog-post__footer-tags-list">
                    <a href="#">{{ post.tags.name }}</a>
                  </div>
                </div>
                <div class="blog-post__footer-social">
                  <span>Share:</span>
                  <div class="blog-post__footer-social-icons">
                    <a href="#">
                      <svg>
                        <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#icon-facebook"></use>
                      </svg>
                    </a>
                    <a href="#">
                      <svg>
                        <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#icon-twitter"></use>
                      </svg>
                    </a>
                    <a href="#">
                      <svg>
                        <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#icon-google"></use>
                      </svg>
                    </a>
                    <a href="#">
                      <svg>
                        <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#icon-pinterest"></use>
                      </svg>
                    </a>
                  </div>
                </div>
              </div>
              <div class="blog-post__author">
                <div class="blog-post__author-avatar">
                  <img src="{% static 'blog/img/user_avatar.png' %}" alt="Author">
                </div>
                <div class="blog-post__author-info">
                  <h5>Written by TZH</h5>
                  <p>This is some trash talk, just for fun.</p>
                  <div class="blog-post__author-info-social">
                    <a href="#">
                      <svg>
                        <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#icon-facebook"></use>
                      </svg>
                    </a>
                    <a href="#">
                      <svg>
                        <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#icon-twitter"></use>
                      </svg>
                    </a>
                    <a href="#">
                      <svg>
                        <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#icon-google"></use>
                      </svg>
                    </a>
                    <a href="#">
                      <svg>
                        <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#icon-pinterest"></use>
                      </svg>
                    </a>
                    <a href="#">
                      <svg>
                        <use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#icon-instagram"></use>
                      </svg>
                    </a>
                  </div>
                </div>
              </div>
              <div class="blog-post__nav">
                <a class="blog-post__nav-previous" href="#">
                  <span class="blog-post__nav-previous-link">Previous Post</span>
                  <span>Why Glass Had Been So Popular Till Now?</span>
                </a>
                <a class="blog-post__nav-next" href="#">
                  <span class="blog-post__nav-next-link">Next Post</span>
                  <span>All You Need To Know About Forest</span>
                </a>
              </div>
              <div class="blog-post__related">
                <div class="blog-post__related-item">
                  <a href="#">
                    <img src="img/img0.jpg" alt="Why Glass Had Been So Popular Till Now?">
                    <h6>Why Glass Had Been So Popular Till Now?</h6>
                  </a>
                  <span>November 16, 2018</span>
                </div>
              </div>
              <div class="blog-post__comments">
                <h5>3 Comments</h5>
                <ul class="blog-post__comments-list">
                  <li class="blog-post__comments-item">
                    <div class="blog-post__comments-item-body">
                      <div class="blog-post__comments-item-avatar">
                        <img src="{% static 'blog/img/user_avatar.png' %}" alt="Comment Author">
                      </div>
                      <div class="blog-post__comments-item-right">
                        <div class="blog-post__comments-item-reply">
                          <a href="#">Reply</a>
                        </div>
                        <div class="blog-post__comments-item-info">
                          <div class="blog-post__comments-item-info-author">
                            <span>
                              <a href="#">评论功能待实现</a>
                            </span>
                          </div>
                          <div class="blog-post__comments-item-info-date">
                            <span>
                              <a href="#">November 25, 2018 at 2:24 pm</a>
                            </span>
                          </div>
                        </div>
                        <div class="blog-post__comments-item-post">
                          <p>待实现</p>
                        </div>
                      </div>
                    </div>
                    <ul class="blog-post__comments-children">
                      <li class="blog-post__comments-item">
                        <div class="blog-post__comments-item-body">
                          <div class="blog-post__comments-item-avatar">
                            <img src="{% static 'blog/img/user_avatar.png' %}" alt="Comment Author">
                          </div>
                          <div class="blog-post__comments-item-right">
                            <div class="blog-post__comments-item-reply">
                              <a href="#">Reply</a>
                            </div>
                            <div class="blog-post__comments-item-info">
                              <div class="blog-post__comments-item-info-author">
                                <span>
                                  <a href="#">Olyvia Becca</a>
                                </span>
                              </div>
                              <div class="blog-post__comments-item-info-date">
                                <span>
                                  <a href="#">September 11, 2018 at 5:35 pm</a>
                                </span>
                              </div>
                            </div>
                            <div class="blog-post__comments-item-post">
                              <p>Aliquet arcu cubilia dignissim natoque posuere vestibulum malesuada integer Ridiculus suscipit justo In tempus penatibus diam arcu dictumst felis scelerisque nunc blandit cubilia condimentum class justo natoque volutpat nam.</p>
                            </div>
                          </div>
                        </div>
                      </li>
                    </ul>
                  </li>
                </ul>
                <div class="blog-post__comments-respond">
                  <h5>Leave a Comment</h5>
                  <form action="single-post.html" method="post">
                    <p class="blog-post__comments-respond-comment">
                      <label for="comment">Comment</label>
                      <textarea id="comment" name="comment" cols="45" aria-required="true"></textarea>
                    </p>
                    <p class="blog-post__comments-respond-author">
                      <label for="author">Name*</label>
                      <input id="author" type="text" name="author" size="30" aria-required="true" required>
                    </p>
                    <p class="blog-post__comments-respond-email">
                      <label for="email-form">Email*</label>
                      <input id="email-form" type="email" name="email-form" size="30" aria-required="true" required>
                    </p>
                    <p class="blog-post__comments-respond-url">
                      <label for="url">Website</label>
                      <input id="url" type="text" name="url" size="30" aria-required="true">
                    </p>
                    <p class="blog-post__comments-respond-submit">
                      <input id="submit" type="submit" name="submit" size="30" value="Post Comment">
                    </p>
                  </form>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
{% endblock container %}

blog_redo/templates/blog/new_post.html
{% extends 'blog/base.html' %}
{% load static %}
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}


{% block container %}
<div class="container">
<div class="col-md-12  col-lg-12">
    <div class="blog-post  blog-post--fullwidth  blog-post--page">
        <div class="blog-post-wrapper  blog-post-wrapper--404">
            <form action="{% url 'blog:new_post' %}" method="post" class="form">
                {% csrf_token %}
                <div class="form-group blog-post__title">
                {% bootstrap_label "标题" label_for="title" %}
                {% bootstrap_field form.title layout='inline' %}
                <small id="emailHelp" class="form-text text-muted">You can say what's so ever you want.</small>
                </div>
                <div class="form-group blog-post__title">
                {% bootstrap_label "作者" label_for="author" %}
                {% bootstrap_field form.author layout='inline' %}
                </div>
                <div class="form-group blog-post__content  blog-post__content--404 ">
                {% bootstrap_label "说" label_for="say so" %}
                {% bootstrap_field form.body layout='inline' %}
                </div>
                <button name="submit" class="btn btn-light">add post</button>
            </form>
        </div>
    </div>
<div>
<div>
{% endblock container %}